# Generated by Django 2.2 on 2020-11-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=2)),
                ('mob', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('odia', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('eng', models.IntegerField()),
            ],
        ),
    ]
